pipeline {
    agent any
    
    parameters {
        string(name: 'ProjectKey', defaultValue: 'petclinic', description: 'SonarQube project key')
        string(name: 'ProjectName', defaultValue: 'petclinic', description: 'SonarQube project name')
        string(name: 'SonarHostUrl', defaultValue: 'http://192.168.201.13:9000/', description: 'SonarQube server URL')
       
    }

    stages {
        stage('Checkout GitHub Repo') {
            steps {
                git 'https://github.com/Noah-linux/DOCKER.git' // Clone the GitHub repository
            }
        }

        stage('Compile Code') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn compile' // Compile the code
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn test' // Run the tests
                }
            }
        }

        stage('Build Package') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn -Dmaven.test.failure.ignore=true clean package' // Build the package
                }
            }
        }

        stage('Sonar Static Code Analysis') {
            steps {
                dir('petclinic-app') { // Ensure SonarQube runs within the project directory
                    withCredentials([string(credentialsId: 'jenkins-sonar-token', variable: 'sonar_token')]) {
                        sh """
                        mvn sonar:sonar \
                            -Dsonar.projectKey=${params.ProjectKey} \
                            -Dsonar.projectName='${params.ProjectName}' \
                            -Dsonar.host.url=${params.SonarHostUrl} \
                            -Dsonar.login=${sonar_token}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            dir('petclinic-app') {
                junit '**/target/surefire-reports/TEST-*.xml' // Archive JUnit test results
                archiveArtifacts 'target/*.jar' // Archive JAR files
            }
        }

      

        cleanup {
            cleanWs() // Clean up workspace
        }
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '3')) // Rotate logs, keep builds for 3 days
    }
}